apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    author: mostafa-shehata
spec:
  selector:
    matchLabels:
      author: mostafa-shehata
  replicas: 3 # Number of replicas --you can use command kubectl scale to scale up and down this
  strategy:
    type: RollingUpdate # Two types:: - Recreate - RollingUpdate (by default)
  template: # Template of pod
    metadata:
      name: web-app-pod
      labels:
        author: mostafa-shehata
    spec:
      containers:
        - image: zeroouser/nginx
          name: web-app-container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"