apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod # name of pod
  labels:
    author: mostafa-shehata
spec:
  containers: # array of containers
    - image: zeroouser/nginx # Image you want to install in container (pulling it if doesn't exist)
      name: web-app-container
      imagePullPolicy: IfNotPresent # don't check for updates if the image exists
      resources:
        limits: # maximum resources
          memory: "512Mi"
          cpu: "1"