apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: nginx-pod
spec:
  containers:
    - image: zeroouser/nginx
      name: web-app-container
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"