# NodePort
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    author: mostafa-shehata
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30006
