on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      - name: "Login to Docker"
        run: docker login -u ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
      - name: "Building docker img"
        run: docker build -t ${{ secrets.USERNAME }}/nginx .
      - name: "pushing to docker hub"
        run: docker push ${{ secrets.USERNAME }}/nginx